###**Conjunto de datos bancarios - Objetivos de marketing**

Los depósitos a plazo son una fuente importante de ingresos para un banco.
Un depósito a plazo es una inversión en efectivo mantenida en una institución financiera. Su dinero se invierte por una tasa de interés acordada durante un período fijo de tiempo o plazo.
El banco tiene varios planes de divulgación para vender depósitos a plazo a sus
clientes, como marketing por correo electrónico, anuncios, marketing telefónico y marketing digital.
Las campañas de marketing telefónico siguen siendo una de las formas más efectivas de llegar a las personas. Sin embargo, requieren una gran inversión, ya que se contratan grandes centros de llamadas para ejecutar estas campañas. Por lo tanto, es crucial identificar a los clientes con más probabilidades de convertir de antemano para que puedan ser dirigidos específicamente a través de una llamada.

**Descripciones detalladas de las columnas**

**Datos del cliente bancario:**

* 1 - edad (numérica)
* 2 - trabajo: tipo de trabajo (categórico: "admin.","desconocido","desempleado","gestión","empleada doméstica","empresario","estudiante", "obrero","autónomo","jubilado","técnico","servicios")
* 3 - marital : estado civil (categórico: "casado", "divorciado", "soltero"; nota: "divorciado" significa divorciado o viudo)
* 4 - Educación (categórica: "desconocido", "secundario", "primario",
"terciario")
* 5 - Incumplimiento: ¿Tiene crédito en mora? (binario: "sí","no")
* 6 - Saldo: Saldo medio anual, en euros (numérico)
* 7 - Vivienda: ¿Tiene préstamo de vivienda? (binario: "sí","no")
* 8 - Préstamo: ¿Tiene préstamo personal? (binario: "sí","no")
**Relacionado con el último contacto de la campaña actual:**
* 9 - Contacto: Tipo de comunicación de contacto (categórico: "desconocido", "teléfono", "celular")
* 10 - día: último contacto día del mes (numérico)
* 11 - mes: último contacto mes del año (categórico: "ene", "feb", "mar", ..., "nov", "dic")
* 12 - duración: duración del último contacto, en segundos (numérico)

 **Otros atributos:**
* 13 - Campaña: número de contactos realizados durante esta campaña y para este cliente (numérico, incluye el último contacto)
* 14 - días: número de días que pasaron después de que el cliente fue contactado por última vez desde una campaña anterior (numérico, -1 significa que el cliente no fue contactado previamente)
* 15 - anterior: número de contactos realizados antes de esta campaña y para este cliente (numérico)
* 16 - Poutcome: resultado de la campaña de marketing anterior (categórico: "desconocido", "otro", "fracaso", "éxito")


**Variable de salida (objetivo deseado):**
* 17 - y - ¿El cliente ha suscrito un depósito a plazo? (binario: "sí","no")

El en la primera estapa de este proyecto se utilizara la parte de test del datase, y luego cuanto se someta el dataset a la parte de evaluacion se podria utilizar el dataset train. Caso que se requiere, se podrian aderir ambos datset con el finde de que pueda arrojar distintos resultados al momento de la evaluacion ya que la divicion entre test y train el programa lo realiza de manera aleatoria

### 1 ) Importmos pandas y librerias para descarga de dataset

In [ ]:
import pandas as pd
import os
import platform
if os.access('test.csv', os.F_OK) is False:
    if platform.system() == 'Windows':
        !curl https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Banking%20Dataset%20-%20Marketing%20Targets/test.csv
    else:
        !wget https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Banking%20Dataset%20-%20Marketing%20Targets/test.csv

--2023-09-06 18:02:51--  https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Banking%20Dataset%20-%20Marketing%20Targets/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 461474 (451K) [text/plain]
Saving to: ‘test.csv.1’

test.csv.1          100%[===================>] 450.66K  --.-KB/s    in 0.01s

2023-09-06 18:02:51 (34.7 MB/s) - ‘test.csv.1’ saved [461474/461474]

### 2) Veamos las 5 primeras filas del dataset

In [ ]:
df1 = pd.read_csv('test.csv',sep = ';')
df1.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

### 3) Veamos cuantas filas y columnas tiene el dataset

In [ ]:
df1.shape

(4521, 17)

### 4) Veamos el tipo de dato de cada columna

In [ ]:
df1.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

### 5) Veamos la cantiad de nulos que tiene el dataset

In [ ]:
df1.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

### **Predicción de costos en la adquisición de clientes.**

PREDECIR EL COSTO DE LAS CAMPAÑAS DE MEDIOS EN FOOD MART DE USA
SOBRE LA BASE DE LOS INGRESOS DE LOS CLIENTES DE 60K, PRODUCTOS, PROMOCIONES Y CARACTERÍSTICAS DE LA TIENDA.

** Descripcion de las 20 variables ms importants del dataset**

* 1) food_category -- etapa del dia en la que se consume generalmente esa comida
* 2) food_department	-- tipo de almacenamento de la comida
* 3) food_family	-- tipo de comida para la familia
* 4) store_sales(in millions)	-- ventas en tienda
* 5) store_cost(in millions)	--costo de la tienda
* 6) unit_sales(in millions)	--  unidades vendidas
* 7) promotion_name	-- nombre de la promocion
* 8) sales_country	-- venta por pais
* 9) marital_status	--
* 10) gender	-- genero
* 11) grocery_sqft	--
* 12) frozen_sqft
* 13) meat_sqft
* 14) coffee_bar
* 15) video_store
* 16) salad_bar
* 17) prepared_food
* 18) florist
* 19) media_type
* 20) cost

### 1 ) Importmos librerias para descarga de dataset

In [ ]:
if os.access('media prediction and its cost.csv.csv', os.F_OK) is False:
    if platform.system() == 'Windows':
        !curl https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Cost%20Prediction%20on%20acquiring%20Customers/media%20prediction%20and%20its%20cost.csv
    else:
        !wget https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Cost%20Prediction%20on%20acquiring%20Customers/media%20prediction%20and%20its%20cost.csv

--2023-09-06 18:02:52--  https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Cost%20Prediction%20on%20acquiring%20Customers/media%20prediction%20and%20its%20cost.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16667988 (16M) [text/plain]
Saving to: ‘media prediction and its cost.csv.1’

media prediction an 100%[===================>]  15.90M  --.-KB/s    in 0.06s

2023-09-06 18:02:52 (255 MB/s) - ‘media prediction and its cost.csv.1’ saved [16667988/16667988]

### 2) Veamos las 5 primeras filas del dataset

In [ ]:
df2 = pd.read_csv('media prediction and its cost.csv', sep = ',')
df2.head()

,food_category,food_department,food_family,store_sales(in millions),store_cost(in millions),unit_sales(in millions),promotion_name,sales_country,marital_status,gender,...,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,media_type,cost
0,Breakfast Foods,Frozen Foods,Food,7.36,2.7232,4.0,Bag Stuffers,USA,M,F,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",126.62
1,Breakfast Foods,Frozen Foods,Food,5.52,2.5944,3.0,Cash Register Lottery,USA,M,M,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",59.86
2,Breakfast Foods,Frozen Foods,Food,3.68,1.3616,2.0,High Roller Savings,USA,S,F,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",84.16
3,Breakfast Foods,Frozen Foods,Food,3.68,1.1776,2.0,Cash Register Lottery,USA,M,F,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,In-Store Coupon,95.78
4,Breakfast Foods,Frozen Foods,Food,4.08,1.4280,3.0,Double Down Sale,USA,M,M,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,Radio,50.79

### 3) Veamos cuantas filas y columnas tiene el dataset

In [ ]:
df2.shape

(60428, 40)

### 4) Veamos el tipo de dato de cada columna

In [ ]:
df2.dtypes

food_category                  object
food_department                object
food_family                    object
store_sales(in millions)      float64
store_cost(in millions)       float64
unit_sales(in millions)       float64
promotion_name                 object
sales_country                  object
marital_status                 object
gender                         object
total_children                float64
education                      object
member_card                    object
occupation                     object
houseowner                     object
avg_cars_at home(approx)      float64
avg. yearly_income             object
num_children_at_home          float64
avg_cars_at home(approx).1    float64
brand_name                     object
SRP                           float64
gross_weight                  float64
net_weight                    float64
recyclable_package            float64
low_fat                       float64
units_per_case                float64
store_type                     object
store_city                     object
store_state                    object
store_sqft                    float64
grocery_sqft                  float64
frozen_sqft                   float64
meat_sqft                     float64
coffee_bar                    float64
video_store                   float64
salad_bar                     float64
prepared_food                 float64
florist                       float64
media_type                     object
cost                          float64
dtype: object

### 5) Veamos la cantiad de nulos que tiene el dataset

In [ ]:
df2.isnull().sum()

food_category                 0
food_department               0
food_family                   0
store_sales(in millions)      0
store_cost(in millions)       0
unit_sales(in millions)       0
promotion_name                0
sales_country                 0
marital_status                0
gender                        0
total_children                0
education                     0
member_card                   0
occupation                    0
houseowner                    0
avg_cars_at home(approx)      0
avg. yearly_income            0
num_children_at_home          0
avg_cars_at home(approx).1    0
brand_name                    0
SRP                           0
gross_weight                  0
net_weight                    0
recyclable_package            0
low_fat                       0
units_per_case                0
store_type                    0
store_city                    0
store_state                   0
store_sqft                    0
grocery_sqft                  0
frozen_sqft                   0
meat_sqft                     0
coffee_bar                    0
video_store                   0
salad_bar                     0
prepared_food                 0
florist                       0
media_type                    0
cost                          0
dtype: int64

### **Predicción de clientes de tarjetas de crédito**

Un gerente del banco está perturbado con clientes que abandonan sus servicios de tarjeta de crédito. Predecir quién va a abandonar el uso de la tarjeta de credito para que puedan recurrir al cliente para brindarles mejores servicios y cambiar las decisiones de los clientes en la dirección opuesta.

**Columnas**
* 1)CLIENTNUM--	Número de cliente. Identificador único para el cliente titular de la cuenta
* 2) Attrition_Flag--	Variable de evento interno (actividad del cliente): si la cuenta está cerrada, 1 else 0
* 3) Customer_Age--	Variable demográfica - Edad del cliente en años
* 4) Género --	Variable demográfica - M=Hombre, F=Mujer
* 5) Dependent_count--	Variable demográfica - Número de dependientes
* 6) Education_Level -- 	Variable demográfica: calificación educativa del titular de la cuenta (ejemplo: escuela secundaria, graduado universitario, etc.)
* 7) Marital_Status--	Variable demográfica - Casado, Soltero, Divorciado, Desconocido
* 8) Income_Category--	Variable demográfica - Categoría de ingresos anuales del titular de la cuenta (< $40K, $40K - 60K, $60K - $80K, $80K-$120K, >
* 9) Card_Category--	Variable de producto - Tipo de tarjeta (azul, plata, oro, platino)
* 10) Months_on_book--	Periodo de relación con el banco
* 11) Total_Relationship_count--	Total no. de productos en poder del cliente
* 12) Months_Inactive_12_mon --	No. de meses inactivos en los últimos 12 meses
* 13) Contacts_Count_12_mon --	No. de contactos en los últimos 12 meses
* 14) Credit_Limit--	Límite de crédito en la tarjeta de crédito
* 15) Total_Revolving_Bal--	Saldo rotativo total en la tarjeta de crédito
* 16) Avg_Open_To_Buy--	Línea de crédito abierta para comprar (promedio de los últimos 12 meses)
* 17) Total_Amt_Chng_Q4_Q1--	Cambio en el monto de la transacción (Q4 sobre Q1)
* 18) Total_Trans_Amt--	Monto total de la transacción (últimos 12 meses)
* 19) Total_Trans_Ct--	Recuento total de transacciones (últimos 12 meses)
* 20) Total_Ct_Chng_Q4_Q1--	Cambio en el recuento de transacciones (Q4 sobre Q1)
* 21) Avg_Utilization_Ratio--	Índice medio de utilización de la tarjeta
* 22) Naive_Bayes_Classifier_attribution--	Bayes ingenuo

### 1 ) Importmos librerias para descarga de dataset

In [ ]:
if os.access('BankChurners.csv', os.F_OK) is False:
    if platform.system() == 'Windows':
        !curl https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Credit%20Card%20Customers%20Prediction/BankChurners.csv
    else:
        !wget https://raw.githubusercontent.com/Aiminoe/datasetcoderdatacsience/main/Credit%20Card%20Customers%20Prediction/BankChurners.csv

### 2) Veamos las 5 primeras filas del dataset

In [ ]:
df3 = pd.read_csv('BankChurners.csv', sep = ',')
df3.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

### 3) Veamos cuantas filas y columnas tiene el dataset

In [ ]:
df3.shape

(10127, 23)

### 4) Veamos el tipo de dato de cada columna

In [ ]:
df3.dtypes

CLIENTNUM                                                                                                                               int64
Attrition_Flag                                                                                                                         object
Customer_Age                                                                                                                            int64
Gender                                                                                                                                 object
Dependent_count                                                                                                                         int64
Education_Level                                                                                                                        object
Marital_Status                                                                                                                         object
Income_Category                                                                                                                        object
Card_Category                                                                                                                          object
Months_on_book                                                                                                                          int64
Total_Relationship_Count                                                                                                                int64
Months_Inactive_12_mon                                                                                                                  int64
Contacts_Count_12_mon                                                                                                                   int64
Credit_Limit                                                                                                                          float64
Total_Revolving_Bal                                                                                                                     int64
Avg_Open_To_Buy                                                                                                                       float64
Total_Amt_Chng_Q4_Q1                                                                                                                  float64
Total_Trans_Amt                                                                                                                         int64
Total_Trans_Ct                                                                                                                          int64
Total_Ct_Chng_Q4_Q1                                                                                                                   float64
Avg_Utilization_Ratio                                                                                                                 float64
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1    float64
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2    float64
dtype: object

### 5) Veamos la cantiad de nulos que tiene el dataset

In [ ]:
df2.isnull().sum()

food_category                 0
food_department               0
food_family                   0
store_sales(in millions)      0
store_cost(in millions)       0
unit_sales(in millions)       0
promotion_name                0
sales_country                 0
marital_status                0
gender                        0
total_children                0
education                     0
member_card                   0
occupation                    0
houseowner                    0
avg_cars_at home(approx)      0
avg. yearly_income            0
num_children_at_home          0
avg_cars_at home(approx).1    0
brand_name                    0
SRP                           0
gross_weight                  0
net_weight                    0
recyclable_package            0
low_fat                       0
units_per_case                0
store_type                    0
store_city                    0
store_state                   0
store_sqft                    0
grocery_sqft                  0
frozen_sqft                   0
meat_sqft                     0
coffee_bar                    0
video_store                   0
salad_bar                     0
prepared_food                 0
florist                       0
media_type                    0
cost                          0
dtype: int64